# Just like the config/database.yml this file requires an entry for each environment
  # http://aws.amazon.com/security-credentials

  development:
  	bucket: barslice
    access_key_id: AKIAJ5GOOLEVIVUV36ZA
    secret_access_key: 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

  test:
    <<: *development

  production:
    <<: *development
